<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ЛБ_1</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.2.1" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.5" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\MSI\Desktop\3 курс 2 семестр\4 курс\куз\лб 1\ЛБ 1\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\MSI\Desktop\3 курс 2 семестр\4 курс\куз\лб 1\ЛБ 1\.editorconfig" />
  </ItemGroup>

</Project>
